version: '3.7'
services:
  fontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
    - 5000:3000
    expose:
      - 3000
    volumes:
      - ./client:/client
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3030
    expose:
      - 3030
    volumes:
      - ./server:/server
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
    - ./mongo-volume:/data/db
    ports:
      - 27027:27017